name: myjournal
version: '1.0'
summary: Open, Secure, Safe, yours
description: |
  MyJournal easily encrypts your physical journals into a journal accessable only by you and people you want to see it.
confinement: devmode
base: core18
parts:
  myjournal:
    plugin: python
    python-version: python3
    source: https://github.com/convexpolygon/MyJournal.git
    stage-packages:
    - python-six

apps:
